---
abstract: 'Perl binding of libfuzzy(ssdeep)'
author:
  - 'Hideaki Ohno <hide.o.j55 {at} gmail.com>'
build_requires:
  Devel::CheckLib: 0.04
  ExtUtils::CBuilder: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::CheckLib: 0.01
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::XSUtil: 1.00
configure_requires:
  Devel::CheckLib: 0.04
  ExtUtils::ParseXS: 2.21
  Module::Build: 0.40
  Module::Build::Pluggable: 0
  Module::Build::Pluggable::CPANfile: 0.04
  Module::Build::Pluggable::CheckLib: 0.01
  Module::Build::Pluggable::GithubMeta: 0
  Module::Build::Pluggable::XSUtil: 1.00
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-FuzzyHash
no_index:
  directory:
    - t
    - xt
    - inc
    - eg
provides:
  Data::FuzzyHash:
    file: lib/Data/FuzzyHash.pm
    version: 0.01
requires:
  XSLoader: 0.02
  perl: 5.008008
resources:
  bugtracker: https://github.com/hideo55/Data-FuzzyHash/issues
  homepage: https://github.com/hideo55/Data-FuzzyHash/tree
  repository: git://github.com/hideo55/Data-FuzzyHash.git
version: 0.01
x_test_requires:
  Test::More: 0.98
